### ISSUE TITLE
Object Oriented Programming

### ISSUE THREAD

**Issue by mdwiltfong** [Holiv/programando-aos-30-v5.0#1]
I love the structure of this project, and the fact that it is able to represent your journey to computer science.

At the moment your JavaScript has a functional approach to creating the branch, and the commits. As someone who is looking at the code for the first time, this can be a lot. I was thinking maybe a more object oriented approach might be useful?

I suggest using JavaScript Classes to create the branchs, and the commits. I will create a PR in the upcoming days as an example.

**Comment by Holiv** [comment]
Thank you for your support, Michael. 
I will be waiting for your PR to learn from it and of course i am going to implementing it on a code refactoring. It will be amazing to see OOP in a real situation.

To be honest i still don't have enough knowledge on OOP to fully implementing it, but is just a matter of time. My progress with JavaScript is completely registered [here in my Notion notes](https://www.notion.so/The-Complete-JavaScript-Course-8c76c6a65eee4faeb8fdcd0f30bdc3a4). 
I am following this [roadmap](https://github.com/Holiv/roadmap-helton-oliveira) i created and [this is the JavaScript course im enrolled](https://www.udemy.com/course/the-complete-javascript-course/). I will start learn OOP in the next few sections and i can't wait to learn it and be really good on it. 

The good point on all of it is that a refactoring of the website from a functional to OOP approach will be a good record of my progress to become a good developer. 

Thanks again and i will be more active on DCC, bringing more updates about this project and asking for help and learning from you guys.

**Comment by Holiv** [comment]
Thank you for your support, Michael.
I will be waiting for your PR to learn from it and of course i am going to implement it on a code refactoring.

To be honest i still don't have enough knowledge on OOP to fully implement it, but it's just a matter of time. My progress with JavaScript is completely registered [here in my Notion notes](https://www.notion.so/The-Complete-JavaScript-Course-8c76c6a65eee4faeb8fdcd0f30bdc3a4).
I am following this [roadmap](https://github.com/Holiv/roadmap-helton-oliveira) i created and this is the [JavaScript course](https://www.udemy.com/course/the-complete-javascript-course/) im enrolled. I will start learn OOP in the next few sections and i can't wait to learn it and be really good on it.

The good point on all of it is that a refactoring of the website from a functional to OOP approach will be a good record of my progress to become a good developer.

I will be more active on DCC bringing more updates about this project and asking for help some times. It would be great to have you guys as part of it. Thanks again.
